name: policyReader
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - comm=0.2.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - executing=2.2.1
  - fontconfig=2.15.0
  - freetype=2.13.3
  - gettext=0.21.0
  - git-lfs=3.7.1
  - icu=75.1
  - ipykernel=7.1.0
  - ipython_pygments_lexers=1.1.1
  - jansson=2.14
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libboost=1.88.0
  - libcurl=8.17.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.1
  - libnsl=2.0.1
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nspr=4.37
  - nss=3.117
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pip=25.3
  - pixman=0.46.4
  - poppler=25.07.0
  - poppler-data=0.4.12
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.0
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - fastapi==0.128.0
      - uvicorn[standard]==0.40.0
      - python-multipart==0.0.21
      - pydantic==2.12.4
      - python-dotenv==1.2.1
      - streamlit==1.52.2
      - numpy==2.3.5
      - torch==2.4.0+cu121
      - torchvision==0.19.0+cu121
      - flash-attn==2.7.4.post1
      - transformers==4.49.0
      - colpali-engine==0.1.1
      - pdf2image==1.17.0
      - pillow==12.0.0
      - tqdm==4.67.1
      - weasyprint==67.0
      - pdfkit==1.0.0
      - openai==2.8.1
      - requests==2.32.5
prefix: /home/zechuan/miniconda3/envs/mDocAgent
